package txt

import (
	"io/ioutil"
	"testing"

	"github.com/kylelemons/godebug/diff"
)

// Meatier lorum ipsum generated by https://baconipsum.com
const textBlock = `


	Bacon ipsum dolor amet minim beef picanha chuck, incididunt aute id consequat
	ex porchetta aliquip adipisicing rump tri-tip. Picanha buffalo exercitation
	nulla tempor shank, commodo ut adipisicing. Enim elit sunt do in picanha.
	Dolore ham biltong strip steak dolore ipsum nostrud.

			In ham hock ad ex pig labore. Cupidatat bresaola pork loin
			occaecat excepteur rump incididunt laboris eiusmod ut ground
			round salami.  Consectetur ex aliquip doner elit turkey brisket.
			Sausage tri-tip ad kielbasa quis rump. Tri-tip nostrud aute,
			esse ham occaecat jerky. Swine ex picanha, non sint t-bone
			commodo porchetta.

	Tri-tip nulla prosciutto deserunt corned beef. Doner alcatra shankle nostrud
	labore officia. Filet mignon rump swine, jerky tenderloin corned beef qui
	shoulder beef ribs buffalo ground round meatball fugiat salami. Aute cillum
	kevin meatloaf exercitation minim deserunt spare ribs boudin sausage. Irure
	non kielbasa strip steak jowl, aliqua incididunt deserunt leberkas lorem
	turkey.  Veniam aute lorem salami, jerky sed tail short loin.


`

func TestFit(t *testing.T) {
	data, err := ioutil.ReadFile("testdata/result.txt")
	if err != nil {
		t.Fatal(err)
	}

	want := string(data)

	if got := Fit(textBlock); got != want {
		t.Errorf("text mismatch - diff follows:\n%s", diff.Diff(got, want))
	}

	/*
		if err := ioutil.WriteFile("testdata/result.txt", []byte(text), 0644); err != nil {
			t.Fatal(err)
		}
	*/
}
